[profiles.sway]
vars = ["sway/vars.toml", "sway/themes/syl.toml"]
posthooks = ["makoctl reload", "sway reload"]

[profiles.sway.dots]
foot = { source = "sway/config/foot", target = ".config/foot" }
kanshi = { source = "sway/config/kanshi", target = ".config/kanshi" }
waybar = { source = "sway/config/waybar", target = ".config/waybar" }
swaylock = { source = "sway/config/swaylock", target = ".config/swaylock" }
mako = { source = "sway/config/mako", target = ".config/mako" }
nvim = { vars = "sway/themes/syl.toml" }
gtk = { source = "sway/config/gtk-3.0/settings.ini", target = ".config/gtk-3.0/settings.ini" }
rofi = { source = "sway/config/rofi", target = ".config/rofi" }
powercord = { source = "sway/config/powercord/theme", target = ".powercord/src/Powercord/themes/theme"}
# eww = { source = "sway/config/eww", target = ".config/eww" }
sway = { source = "sway/config/sway", target = ".config/sway" }
