# NOTICE: gtk-3.0 has only settings.ini linked, for 
[profiles.sway]
vars = ["sway/vars.toml", "sway/themes/aquarium.toml"]
posthooks = ["sway reload", "makoctl reload", "killall -SIGUSR1 kitty"]

[profiles.sway.dots]
##config
kitty = { source = "sway/config/kitty", target = ".config/kitty" }
sway = { source = "sway/config/sway", target = ".config/sway" }
# kanshi = { source = "sway/config/kanshi", target = ".config/kanshi" }
waybar = { source = "sway/config/waybar", target = ".config/waybar" }
swaylock = { source = "sway/config/swaylock", target = ".config/swaylock" }
mako = { source = "sway/config/mako", target = ".config/mako" }
oguri = { source = "sway/config/oguri", target = ".config/oguri" }
nvim = { vars = "sway/themes/aquarium.toml"}
gtk = { source = "sway/config/gtk-3.0/settings.ini", target = ".config/gtk-3.0/settings.ini" }
rofi = { source = "sway/config/rofi", target = ".config/rofi" }
powercord = { source = "sway/config/powercord/theme", target = ".powercord/src/Powercord/themes/theme"}
zshenv = { source = "sway/config/zsh/zshenv", target = ".zshenv" }
