# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
# - `sheldon add` to add a new plugin to the config file - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

[plugins]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
manpath = { value = 'export MANPATH="{{ dir }}":$MANPATH', each = true}

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Plugins OHMYZSH
[plugins.omz-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"

[plugins.omz-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{git,pip,archlinux,sudo}.plugin.zsh"]

[plugins.omz-nvm]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["nvm.plugin.zsh"]
apply = ["defer"]

# Else
[plugins.fsyh]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.wd]
github = "ExtinctAxolotl/wd"
apply = ["fpath", "source", "manpath"]

[plugins.auto-ls]
github = 'desyncr/auto-ls'
use = ['auto-ls.zsh']

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

[plugins.rust-completions]
github = "ryutok/rust-zsh-completions"
