# ~/.dotfiles/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = ".dotfiles"
gpg_user_id = "mrsosaki@posteo.net"

[settings]
vars = [ "vars.toml" ]
hooks = ["nvim --headless +PackerCompile +sleep 1 +qall"]

[settings.dots]
# REMINDER:
# A dot entry representing a symlink, `source` is relative to `dotfiles_dir` 
# and `target` shall be relative to $HOME directory or absolute.

# === CONFIG ===
# nvim
nvim = { source = "src/config/nvim", target = ".config/nvim" }

# alacritty
alacritty = { source = "src/config/alacritty", target = ".config/alacritty" }

# sheldon
sheldon = { source = "src/config/sheldon/plugins.toml", target = ".config/sheldon/plugins.toml" }

# starship
starship = { source = "src/config/starship.toml", target = ".config/starship.toml" }

# === HOME ===
# spacevim
spacevim = { source = "src/home/SpaceVim/init.toml", target = ".SpaceVim.d/init.toml" }

# atom
atom = { source = "src/home/atom/config.cson", target = ".atom/config.cson" }

# bash
bash = { source = "src/home/bashrc", target = ".bashrc" }

# taskrc
task = { source = "src/home/taskrc", target = ".taskrc" }

# vimrc (based on @adi1090x archcraft vimrc)
vim = { source = "src/home/vimrc", target = ".vimrc" }

# zshrc
zsh = { source = "src/home/zshrc", target = ".zshrc"}

# git
git = { source = "src/home/gitconfig", target = ".gitconfig"}

# wd
wd = { source = "src/home/warprc", target = ".warprc"}

# neofetch 
neofetch = { source = "src/config/neofetch/", target = ".config/neofetch" }

# kitty
kitty = { source = "src/config/kitty/", target = ".config/kitty" }

# awesome
# awesome = { source = "src/config/awesome", target = ".config/awesome"} 

# === IMPORTS ===
[[import]]
path = "tokyonight/tokyonight.toml"
