# ~/.dotfiles/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = ".dotfiles"
# gpg_user_id = "mrsosaki@posteo.net"

[settings]
vars = []
posthooks = ["nvim --headless +PackerCompile +sleep1 +qall"]

[settings.dots]
# === CONFIG ===
nvim = { source = "src/config/nvim", target = ".config/nvim", vars = "src/config/nvim/vars.toml" }
sheldon = { source = "src/config/sheldon", target = ".config/sheldon" }
starship = { source = "src/config/starship.toml", target = ".config/starship.toml" }
macchina = { source = "src/config/macchina", target = ".config/macchina" }
kitty = { source = "src/config/kitty/", target = ".config/kitty" }
bash = { source = "src/config/bash/bashrc", target = ".bashrc" }
zshrc = { source = "src/config/zsh/zshrc", target = ".zshrc" }
zsh = { source = "src/config/zsh/zsh", target = ".zsh" }
git = { source = "src/config/git", target = ".config/git" }
dircolors = { source = "src/config/zsh/dircolors", target = ".config/dircolors" }

# === IMPORTS ===
[[import]]
path = "sway/sway.toml"
