spacing=1
padding=0
hide_ascii=true
prefer_small_ascii=true
separator="→ "

[palette]
type="Full"
glyph=" "
visible=true

[bar]
glyph="o"
symbol_open='O'
symbol_close='O'
hide_delimiters=false
visible=true

[box]
title="*nix"
border="rounded"
visible=true

[box.inner_margin]
x=5
y=3

[randomize]
key_color=true
separator_color=true
pool="base"

[keys]
host            = "host"
kernel          = "kernel"
battery         = "battery"
os              = "os"
de              = "de"
wm              = "wm"
distro          = "distro"
terminal        = "term"
shell           = "sh"
packages        = "packages"
uptime          = "up"
memory          = "memory"
machine         = "machina"
local_ip        = "ip"
backlight       = "backlight"
resolution      = "res"
cpu_load        = "cpuload"
cpu             = "cpu"
