# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
# - `sheldon add` to add a new plugin to the config file - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

[plugins]

# Plugins OHMYZSH
[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{git,nvm,pip,archlinux,sudo,taskwarrior}.plugin.zsh"]

# Else
[plugins.FsYH]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.wd]
github = "mfaerevaag/wd"
apply = ["fpath", "source"]

# [plugins.autopair]
# github = "hlissner/zsh-autopair"
# use = [ "autopair.zsh" ]

[plugins.auto-ls]
github = 'desyncr/auto-ls'
use = ['auto-ls.zsh']

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.rust-completions]
github = "ryutok/rust-zsh-completions"
# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
