[profiles.autumn]
vars = [ "autumn/vars.toml"]
hooks = ["i3-msg restart", "killall -q picom", "picom -b"] # yes ik very ugly but it works... FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUCK

[profiles.autumn.dots]
i3 = { source = "autumn/config/i3", target = ".config/i3" }
kitty = { source = "autumn/config/kitty", target = ".config/kitty" }
dunst = { source = "autumn/config/dunst", target = ".config/dunst" }
picom = { source = "autumn/config/picom", target = ".config/picom" }
rofi =  { source = "autumn/config/rofi", target = ".config/rofi" }
polybar = { source = "autumn/config/polybar", target = ".config/polybar" }
