# system
# ============
terminal = "kitty"
home_dir = "/home/axolotl/"
corner_rad = "15.0"

# hardware
# ========
battery = "BAT0"
adapter = "AC"
main_monitor = "eDP1" # for polybar
wire_face = "enp2s0" # wired interface
wireless_face = "wlan0" # wireless interface

# colors
# ======
# 'UI'
bg = "#0c0310" # Default Background
bg_alt = "#14051A" # Lighter Background
bg_alter = "#1B0724"
fg = "#E7DDCB" # Default foreground
fg_alt = "#F3EEE5" # Lighter foreground
fg_alter = "#F9F7F2" # Lighter foreground
fg_altest = "#FAFAFA" # Lighter foreground

cursor = "%fg"
# colors
black = "#303030"
white = "#E7DDCB"

# colorful colors (naming choices)
red = "#A72D2F"
green = "#94B86B"
yellow = "#E5B47D"
blue = "#504F7D"
magenta = "#804471"
cyan = "#448278"
orange = "#E29870"
pink = "#B2466B"

# colors
# ======
# normal colors
color0  = "%bg"
color1  = "%red"
color2  = "%green"
color3  = "%yellow"
color4  = "%blue"
color5  = "%magenta"
color6  = "%cyan"
color7  = "%white"

# brighter colors
color8  = "%black"
color9  = "%red"
color10  = "%green"
color11  = "%yellow"
color12  = "%blue"
color13  = "%magenta"
color14  = "%cyan"
color15  = "%white"

#extended
color16 = "%orange"
