add_newline = false

[character]
success_symbol = "[ͷ](bold green)"
error_symbol = "[ͷ](bold italic red)"
vicmd_symbol = "[Ͷ](bold purple)"

[line_break]
disabled = true

[jobs]
number_threshold=3

[cmd_duration]
min_time = 50
