## colors
# NOTE: The colors are specified without the "#"
#       for programs like waylock in mind
# grounds 
fg             = "DADAE8"  # #DADAE8 
fg_alt         = "555169"  # #6e6a86
fg_alter       = "6e6a86"  # #6e6a86
bg             = "1E1E29"  # #1E1E29
bg_alt         = "1f1d2e"  # #1f1d2e
bg_alter       = "26233a"  # #26233a
# selection        
slt_fg         = "E5B4E2"  # #E5B4E2
slt_bg         = "332E41"  # #332E41
# specials         
links          = "%magenta"# #c4a7e7
cursor         = "555169"  # #555169
cursor_text    = "%white"   # #e0def4
# tabs             
tab_active_fg  = "%fg"  # #e0def4
tab_active_bg  = "%bg_alter"# #26233a
tab_inactive_fg= "%fg_alt"  # #6e6a86
tab_inactive_bg= "%bg"  # #191724
# specifications    
# _br suffix indicates the brighter version of a color
black          = "6E6C7E"  # #
black_br       = "6E6C7E"  # #
red            = "E38C8F"  # #
red_br         = "E38C8F"  # #
green          = "B1E3AD"  # #
green_br       = "B1E3AD"  # #
yellow         = "EBDDAA"  # #
yellow_br      = "EBDDAA"  # #
blue           = "A4B9EF"  # #
blue_br        = "A4B9EF"  # #
magenta        = "C6AAE8"  # #
magenta_br     = "C6AAE8"  # #
cyan           = "E5B4E2"  # #
cyan_br        = "E5B4E2"  # #
white          = "DADAE8"  # #
white_br       = "DADAE8"  # #

# accents and others
accent         = "%cyan"
accent_alt     = "%cyan_br"

## specifics
# wall
wall="~/.walls/pluswall/rosepinebase.png"

# nvim
nvim_color_name="rose-pine"
nvim_color_url="rose-pine/neovim"
nvim_statusline_name="%nvim_color_name"
nvim_color_style="base"

# applications
gtk_theme="rose-pine-gtk"
cursor_theme="Bibata-Modern-Ice"
icon_theme="Papirus"
