# theme
theme = "jabba"
## colors
# grounds
fg                  = "b2aeae"
fg_alt              = "a4a3a2"
fg_alter            = "91908d"
fg_light            = "c3c1c1"
bg                  = "141414"
bg_alt              = "1a1a1a"
bg_alter            = "1f1f1f"
bg_dark             = "0f0f0f"
# selection             
slt_fg              = "%bg"
slt_bg              = "%fg"
# specials              
links               = "%magenta"
cursor              = "%magenta_br"
cursor_text         = "%fg_light"
# specifications        
black               = "353535"
black_br            = "525252"
red                 = "be3a0e"
red_br              = "df4411"
green               = "507c56"
green_br            = "5f9566"
yellow              = "f97d10"
yellow_br           = "fa9033"
blue                = "314faf"
blue_br             = "3c5dc8"
magenta             = "613e8e"
magenta_br          = "744baa"
cyan                = "506dce"
cyan_br             = "6c84d5"
white               = "d4c4c4"
white_br            = "e1d6d6"

# accents and others
accent              = "%green"
accent_alt          = "%green"

## specifics             
wall                = "~/.walls/pluswall/jabba.png"

# applications           
gtk_theme           = "phocus"
cursor_theme        = "Bibata-Modern-Ice"
icon_theme          = "Papirus"
