## colors
# NOTE: The colors are specified without the "#"
#       for programs like waylock in mind
# grounds 
fg             = "575279"  # #575279
fg_alt         = "9893a5"  # #9893a5
fg_alter       = "6e6a86"  # #6e6a86
bg             = "faf4ed"  # #faf4ed
bg_alt         = "fffaf3"  # #fffaf3
bg_alter       = "f2e9de"  # #f2e9de
# selection       
slt_fg         = "575279"  # #575279
slt_bg         = "eee9e6"  # #eee9e6
# specials         
links          = "%magenta"# #907aa9
cursor         = "9893a5"  # #9893a5
cursor_text    = "%white"  # #e0def4
# tabs             
tab_active_fg  = "575279"  # #575279
tab_active_bg  = "f2e9de"  # #f2e9de
tab_inactive_fg= "6e6a86"  # #6e6a86
tab_inactive_bg= "faf4ed"  # #faf4ed
# specifications    
# _br suffix indicates the brighter version of a color
black          = "907aa9"  # #907aa9
black_br       = "6e6a86"  # #6e6a86
red            = "b4637a"  # #b4637a
red_br         = "eb6f92"  # #eb6f92
green          = "286983"  # #286983
green_br       = "31748f"  # #31748f
yellow         = "ea9d34"  # #ea9d34
yellow_br      = "f6c177"  # #f6c177
blue           = "56949f"  # #56949f
blue_br        = "9ccfd8"  # #9ccfd8
magenta        = "907aa9"  # #907aa9
magenta_br     = "c4a7e7"  # #c4a7e7
cyan           = "d7827e"  # #d7827e
cyan_br        = "ebbcba"  # #ebbcba
white          = "575279"  # #575279
white_br       = "e0def4"  # #e0def4

# accents and others
accent         = "%cyan"
accent_alt     = "%cyan_br"

## specifics
# wall
wall="~/.walls/pluswall/rosepinedawn.png"

# nvim
nvim_color_name="rose-pine"
nvim_color_url="rose-pine/neovim"
nvim_statusline_name="%nvim_color_name"
nvim_color_style="dawn"

# applications
gtk_theme="rose-pine-dawn-gtk"
cursor_theme="Bibata-Modern-Ice"
icon_theme="Papirus"
