## colors - this is solo light
# grounds
fg                  = "141414"
fg_alt              = "0f0f0f"
fg_alter            = "0c0c0c"
fg_light            = "1c1c1c"
bg                  = "B2AEAE"
bg_alt              = "b7b3b3"
bg_alter            = "bab6b6"
bg_dark             = "ada9a9"
# selection             
slt_fg              = "%bg"
slt_bg              = "%fg"
# specials              
links               = "%magenta"
cursor              = "%magenta_br"
cursor_text         = "%fg_light"
# specifications        
black               = "353535"
black_br            = "525252"
red                 = "b63206"
red_br              = "d73c09"
green               = "48744e"
green_br            = "578d5e"
yellow              = "e96d00"
yellow_br           = "ea8023"
blue                = "2947a7"
blue_br             = "3455c0"
magenta             = "593686"
magenta_br          = "6c43a2"
cyan                = "4865c6"
cyan_br             = "6C84D5"
white               = "D4C4C4"
white_br            = "E1D6D6"

# accents and others
accent              = "%green"
accent_alt          = "%green"

## specifics             
wall                = "~/.walls/pluswall/solo.png"

# nvim                   
nvim_color_name     = "solo"
nvim_statusline_name= "axolotl"

# applications           
gtk_theme           = "solo"
cursor_theme        = "Bibata-Modern-Ice"
icon_theme          = "Papirus"
