# syl - the stormlight's theme
theme     = "syl"
## colors
# grounds
fg                  = "F0F0F9"
fg_alt              = "ebebf4"
fg_alter            = "e6e6ef"
fg_light            = "f5f5fe"
bg                  = "07080f"
bg_alt              = "0D0E16"
bg_alter            = "12131D"
bg_dark             = "010104"
# selection              
slt_bg              = "%bg_alt"
# specifications         
black               = "1f1f2d"
black_br            = "242436"
red                 = "D79B9B"
red_br              = "E8B5B5"
green               = "C0D79B"
green_br            = "DAEAC3"
yellow              = "DCCC93"
yellow_br           = "F1E2AC"
blue                = "98A7DE"
blue_br             = "B7C2EC"
magenta             = "BBB0EC"
magenta_br          = "D4CEF6"
cyan                = "B0CDEC"
cyan_br             = "C8DFF5"
white               = "D9E3EF"
white_br            = "DFE8F3"

# accents and others
accent              = "%green"
accent_alt          = "%green_br"

## specifics             
wall                = "~/.walls/pluswall/syl.png"

# applications           
gtk_theme           = "phocus"
cursor_theme        = "Bibata-Modern-Ice"
icon_theme          = "Papirus"
