## colors
# NOTE: for templating
# grounds
fg                  = "" # #
fg_alt              = "" # #
fg_alter            = "" # #
bg                  = "" # #
bg_alt              = "" # #
bg_alter            = "" # #
# selection              
slt_fg              = "" # #
slt_bg              = "" # #
# specials               
links               = "" # #
cursor              = "" # #
cursor_text         = "" # #
# specifications         
black               = "" # #
black_br            = "" # #
red                 = "" # #
red_br              = "" # #
green               = "" # #
green_br            = "" # #
yellow              = "" # #
yellow_br           = "" # #
blue                = "" # #
blue_br             = "" # #
magenta             = "" # #
magenta_br          = "" # #
cyan                = "" # #
cyan_br             = "" # #
white               = "" # #
white_br            = "" # #

# accents and others
accent              = ""
accent_alt          = ""

## specifics             
wall                = ""

# nvim                   
nvim_color_name     = ""
nvim_color_url      = ""
nvim_statusline_name= ""
nvim_color_style    = ""

# applications           
gtk_theme           = ""
cursor_theme        = ""
icon_theme          = ""
