# theme
theme     = ""
## colors
# NOTE: for templating
# grounds
fg                  = ""
fg_alt              = ""
fg_alter            = ""
fg_light            = ""
bg                  = ""
bg_alt              = ""
bg_alter            = ""
bg_dark             = ""
# selection              
slt_fg              = ""
slt_bg              = ""
# specials               
links               = ""
cursor              = ""
cursor_text         = ""
# specifications         
black               = ""
black_br            = ""
red                 = ""
red_br              = ""
green               = ""
green_br            = ""
yellow              = ""
yellow_br           = ""
blue                = ""
blue_br             = ""
magenta             = ""
magenta_br          = ""
cyan                = ""
cyan_br             = ""
white               = ""
white_br            = ""

# accents and others
accent              = ""
accent_alt          = ""

## specifics             
wall                = ""

# applications           
gtk_theme           = ""
cursor_theme        = ""
icon_theme          = ""
